config/routes.rb
Lessboot::Application.routes.draw do

  resources :items

  root 'items#index'

end

app/models/item.rb
class Item < ActiveRecord::Base
  self.per_page = 18
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  def index
    @items = Item.paginate(:page => params[:page])
  end

  # GET /items/1
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:number, :item, :url, :user, :thumbnail, :sales, :rating, :rating_decimal, :cost, :uploaded_on, :last_update, :tags, :category, :live_preview_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/index.html.erb
<header class="header">
  <div class="container">
    <div class="row">
      <h1 class="col-md-3">
        <a href="http://lessboot.herokuapp.com">
          <div class="less">LESS</div>
          <div class="boot">boot</div>
        </a>
      </h1>
      <h4 class="col-md-5 tag">do something
        <span class="tag-diff">different</span> in your next project</h4>
      <div class="col-md-2 col-md-offset-1">
        <a class="link pull-right" href="http://twitter.com/dunckr">
          <h5>♥ by dunckr</h5>
        </a>
      </div>
    </div>
  </div>
</header>

<div class="container-fluid center-block">
  <div class="row">
    <% @items.each do |item| %>
      <a href=<%= "#{item.url}?ref=duncky" %> >
        <div class="col-md-4">
          <div class="box info">
            <div class="row">
              <div class="col-md-3">
                <h4 class="rating">
                  <%= item.rating_decimal %>
                  <small>/5</small>
                </h4>
              </div>
              <div class="col-md-6">
                <h4 class="cost pull-right">
                  <small>$</small>
                  <%= item.cost %></h4>
              </div>
            </div>
            <img class="img-rounded" src=<%= item.live_preview_url %> />
          </div>
        </div>
      </a>
    <% end %>
  </div>
</div>

<footer>
  <div class="container">
    <div class="footer center-block">
      <%= will_paginate @items %>
    </div>
  </div>
</footer>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @item.number %>
</p>

<p>
  <strong>Item:</strong>
  <%= @item.item %>
</p>

<p>
  <strong>Url:</strong>
  <%= @item.url %>
</p>

<p>
  <strong>User:</strong>
  <%= @item.user %>
</p>

<p>
  <strong>Thumbnail:</strong>
  <%= @item.thumbnail %>
</p>

<p>
  <strong>Sales:</strong>
  <%= @item.sales %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @item.rating %>
</p>

<p>
  <strong>Rating decimal:</strong>
  <%= @item.rating_decimal %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @item.cost %>
</p>

<p>
  <strong>Uploaded on:</strong>
  <%= @item.uploaded_on %>
</p>

<p>
  <strong>Last update:</strong>
  <%= @item.last_update %>
</p>

<p>
  <strong>Tags:</strong>
  <%= @item.tags %>
</p>

<p>
  <strong>Category:</strong>
  <%= @item.category %>
</p>

<p>
  <strong>Live preview url:</strong>
  <%= @item.live_preview_url %>
</p>

<%= link_to 'Back', items_path %>

app/views/layouts/_footer.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-47339580-2', 'lessboot.herokuapp.com');
  ga('send', 'pageview');

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lessboot</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag "application", "http://fonts.googleapis.com/css?family=Oswald:400,700" => true %>
  <%= stylesheet_link_tag "application", "http://fonts.googleapis.com/css?family=PT+Mono" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<%= render 'layouts/footer' %>
</body>
</html>